
server:
  port: 8000


spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


logging:
  level:
    root: INFO
    com.netflix.eureka: ERROR
    org.springframework.web: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

