
server:
  port: 8080


spring:
  application:
      name: guobin-oauth



  # 配置Redis
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 5
    timeout: 10000
    password:
    database: 1

  session:
    store-type: redis





  # 把自己注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2



logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

